name = "Tire Deflation Device"
prefix = "tdd"
mainprefix = "z"

[properties]
author = "Ampersand"
url = "https://github.com/ampersand38/tire-deflation-device"

[files]
include = [
    "AUTHORS.txt",
    "LICENSE",
    "logo_ampersand_ca.paa",
    "mod.cpp",
    "README.md"
]
exclude = [
    ".vscode",
    "*.sqfc",
]

[asc]
enabled = true
